### ISSUE TITLE
[skin-settings] re-work categories and items for less clutter

### ISSUE THREAD

**Issue by vonH** [vonH/skin.xperience1080#22]
Re-think the layout of Skin Settings, possibly moving QuickNav into separate category and moving other items around.

**Comment by vonH** [comment]
@xhaggi Your thoughts on this? I've tried different variations and there's nothing else that fits. I'll close and reject unless you have objections.

**Comment by xhaggi** [comment]
we talk about that later.

**Comment by vonH** [comment]
The settings work as they are.
