### ISSUE TITLE
Rss feed overlaps

### ISSUE THREAD

**Issue by CaTzil** [vonH/skin.xperience1080#30]
When the RSS feed is on the bottom, it overlaps other icons
http://i.imgur.com/WmksS03.jpg

**Comment by tungmeister** [comment]
If you edit the Custom_RSS.xml and change the `<posy>` value to 28 it will be sorted though for a proper fix I think it would look better if the power and favorites etc were positioned higher.

Edit: Acutally if you change all occurrences of `<posy>970</posy>`  to `<posy>960</posy>`  and set the rss posy to 20 it looks much more balanced.

**Comment by xhaggi** [comment]
fixed by https://github.com/vonH/skin.xperience1080/commit/59268266cc47fc9470c01b451a9fd38690aad9fe

**Comment by vonH** [comment]
Excellent
