### ISSUE TITLE
[video] enable editing of userrating from the frontend

### ISSUE THREAD

**Issue by xhaggi** [vonH/skin.xperience1080#31]
see https://github.com/xbmc/xbmc/pull/8049 for the necessary changes.

**Comment by xhaggi** [comment]
We also need to output the `ListItem.UserRating` label for both music and video in the related views.
IMO we should first think about a nice way to show both.

**Comment by vonH** [comment]
I can only see an option in video-based areas. Added conditional display after RatingAndVotes to DialogVideoInfo https://github.com/vonH/skin.xperience1080/commit/f9e9d5c6d369166cfce348039a869a2bd980fdb0
