### ISSUE TITLE
[skin] adding missing new windows

### ISSUE THREAD

**Issue by xhaggi** [vonH/skin.xperience1080#33]
The following skin files needs to be added for Jarvis
- [x] EventLog.xml [(info)](http://forum.kodi.tv/showthread.php?tid=231270&pid=2080363#pid2080363)
- [x] DialogAudioDSPManager.xml [(info)](http://forum.kodi.tv/showthread.php?tid=231270&pid=2056843#pid2056843)
- [x] DialogAudioDSPSettings.xml [(info)](http://forum.kodi.tv/showthread.php?tid=231270&pid=2056843#pid2056843)
- [ ] DialogPVRRadioRDSInfo.xml [(info)](http://forum.kodi.tv/showthread.php?tid=231270&pid=2105234#pid2105234)

Piers' edit: Also missing
- [x] DialogMasterModeFreeSurround.xml
- [x] DialogSpeakerDistance.xml
- [x] DialogSpeakerGain.xml
- [x] DialogParametricEQ.xml

**Comment by xhaggi** [comment]
@vonH skin file for event log window was added with a menu item in the power menu.

**Comment by vonH** [comment]
@xhaggi I'll check the styling and review all recent changes. I got your message, sorry I have not yet replied - still recovering from surgery.

**Comment by disrupted** [comment]
@vonH best wishes from a quiet reader ;-) get well soon !

**Comment by xhaggi** [comment]
best wishes from my side too ;)

**Comment by vonH** [comment]
Currently working on DialogAudioDSPManager.xml

**Comment by vonH** [comment]
I want to keep the current layout, with the option on the right, but I'm unsure whether or not it's practical for this window.

@xhaggi your thoughts? (remember this is only the start of the layout, ignore the misaligned textures and text).

![dspmanager](https://cloud.githubusercontent.com/assets/10042301/12256093/8c4783c0-b8f2-11e5-8ad3-d86fee3b8b56.png)

**Comment by xhaggi** [comment]
we should use branches for larger changes like that. We can collaborate nicely and I'm able to test it before we merge it in the master. a pull request for branches like that would be nice too. it can be used to discussion the changes and we are able to use the rebase feature after we change things.

**Comment by xhaggi** [comment]
to answer your question :) i don't know how this dialog looks in confluence, but your screenshot looks good atm

**Comment by vonH** [comment]
Of course I'd submit this to a new branch - only changes I'm certain of I submit to the relevant branch. I'm still working out the layout, it's an ugly dialog as it is - in any skin.

**Comment by vonH** [comment]
I've redesigned it with the items on the left. I'm now testing it with daily use - will up to new branch once done. There are changes to other files (some includes).

**Comment by xhaggi** [comment]
cool ;) .. create a PR assign me and i'll do some testings.

**Comment by vonH** [comment]
DialogAudioDSPManager https://github.com/vonH/skin.xperience1080/commit/f645a4dfe7d512e89904e806668fe0919ae051d8

**Comment by vonH** [comment]
DialogAudioDSPSettings (initial commit) https://github.com/vonH/skin.xperience1080/commit/a31805e6411f477e5743b567dc527e4b9d976a67

**Comment by vonH** [comment]
https://github.com/vonH/skin.xperience1080/commit/10a279427c0ab2cd81870939103c8504dea0d85f

**Comment by vonH** [comment]
https://github.com/vonH/skin.xperience1080/commit/5aec1478bdfc53b86b152b4094d32a5ee782a949
https://github.com/vonH/skin.xperience1080/commit/c283bd6da32074724a8fd5b4ef55e325fcda5f0b
https://github.com/vonH/skin.xperience1080/commit/aa22a23f454b50bbb832c6297c398a1496dc3820

**Comment by vonH** [comment]
All AudioDSP now completed, only PVR remaining @xhaggi
