### ISSUE TITLE
[media] adding missing new icons

### ISSUE THREAD

**Issue by xhaggi** [vonH/skin.xperience1080#34]
The following icons needs to be added for Jarvis.
- [x] DefaultIconInfo.png
- [x] DefaultIconWarning.png
- [x] DefaultIconError.png
- [x] DefaultAddonImages.png
- [x] DefaultAddonAudioDSP.png
- [x] DefaultDVDFull.png

**Comment by vonH** [comment]
Will do

**Comment by vonH** [comment]
@xhaggi DefaultAddonImages.png is already there

**Comment by vonH** [comment]
Are the Info, Warning, Error icons replacement for kaitoast?

**Comment by xhaggi** [comment]
not sure, please take a look at the skin thread for jarvis where ronie listed the new icons

**Comment by vonH** [comment]
Please check three completed icons (we're using the existing disc image as the DVD Full and ROM, I've changed the Empty to a new icon).

**Comment by vonH** [comment]
I checked ronie's thread - it doesn't really provide much further information. I'll ask him or look at the commits.

**Comment by vonH** [comment]
Fixed with https://github.com/vonH/skin.xperience1080/commit/d77c0615759bbe056e74f5d5b77c70cae31c61bc
