### ISSUE TITLE
[media] new button image which indicates a search operation

### ISSUE THREAD

**Issue by xhaggi** [vonH/skin.xperience1080#35]
I need a new button image which indicates a search operation.

`media/buttons/search-fo.png`
`media/buttons/search-nf.png`

same layout like this button:
https://github.com/vonH/skin.xperience1080/blob/master/media/buttons/get-fo.png
https://github.com/vonH/skin.xperience1080/blob/master/media/buttons/get-nf.png

Thanks :smile:

**Comment by vonH** [comment]
A search icon with the blue/grey combination above?

**Comment by xhaggi** [comment]
Focused and not focused like the both images above yeah.

**Comment by vonH** [comment]
@xhaggi What is this for?

**Comment by xhaggi** [comment]
i need it for the pvrinfo dialog where you can trigger a find similar search action.

**Comment by vonH** [comment]
I'm working on textures at the moment - I've just had to set everything up again. Ignore the odd commits.

**Comment by vonH** [comment]
37e09ca3cf28bf672b2d5d447a29af56543e5247 fixes

**Comment by xhaggi** [comment]
great thanks
