### ISSUE TITLE
ive got a few issues needing fixed in the latest xperience1080, thanks

### ISSUE THREAD

**Issue by washingleaves** [vonH/skin.xperience1080#36]
i noticed my favourite view for files mode is gone , which would be the video wall view , ive missed this one ever since xperience1080+ , please integrate this great view

it seems also that i still can only select list view when in my advanced launcher clone ive renamed to comics launcher , which i use for my comics , id appreciate a fix for this as well , thanks

also advanced launcher view > poster view , Posters are too small and the game fanart isnt visible in the background while hovering over a game , the background is simply a solid grey for all games its as if youve disabled fanart while in poster view, it does show in the gameinfo menue itself but not outside while scrolling through games ,please fix this

**Comment by vonH** [comment]
Xperience1080+ was not an official part of this skin. Please log separate issues for each item.
