### ISSUE TITLE
[skin] additional views unlocked for advanced launcher clone

### ISSUE THREAD

**Issue by washingleaves** [vonH/skin.xperience1080#38]
it seems that i still can only select list view when in my advanced launcher clone ive renamed to comics launcher , which i use for my comics , id appreciate a fix for this  , thanks

**Comment by vonH** [comment]
Appears invalid to me, not doing it. You can if you like, @xhaggi

**Comment by xhaggi** [comment]
As a workaround you need to rename the plugin id of your clone to starts with `plugin.program.advanced.launcher`

**Comment by washingleaves** [comment]
well , ive just tried that and all this does is make my advanced launcher clone disappear from the addons menu in kodi ...so not a solution

**Comment by xhaggi** [comment]
then you did something wrong

**Comment by washingleaves** [comment]
nope ive followed youre instructions , heres my addon.xml>
addon id="plugin.program.advanced.launcher" name="Comics Launcher" version="2.5.8" provider-name="Angelscry"

**Comment by xhaggi** [comment]
name it `plugin.program.advanced.launcher2` or `plugin.program.advanced.launcher.clone`, it should starts with `plugin.program.advanced.launcher`

**Comment by xhaggi** [comment]
@washingleaves any news on this?

**Comment by washingleaves** [comment]
nope , dont work , ive renamed the id to plugin.program.advanced.launcher.comics, did this not just for the settings.xml but for the settings.xml in the resources folder and the resources lib folder launcher_plugin.py as well , still can only select list view as viewtype, maybe the skin view settings should be set to ignore anything beyond plugin.program.advanced.launcher   in order to be able to name the clone plugin.program.advanced.launcher.whatever   and still get the full selection of views

**Comment by xhaggi** [comment]
Thanks I'll take a look at this tomorrow or next week to make it possible, thought it's currently the case

**Comment by washingleaves** [comment]
ok , ill wait , thanks, btw while youre at it , do me a big favor and add that video wall view wheve talked about that is in crnis 1080p mod, would appreciate it alot man, its the only reason im still using crnis 1080p skin , which as you can imagine is broken as all hell due to skinning changes in kodi

**Comment by vonH** [comment]
@washingleaves Make a new request, which will get refused. That view will not be supported in Xperience1080 - it doesn't remotely suit the aesthetics.

**Comment by washingleaves** [comment]
it doesnt suit aesthetics? in what way would that possible be? id rather say it does the other way around it adds additional value exspecially for having media such as movies to go through , with its big Poster sized thumbs in an easy to view fashion its a win win situation , please reconsider , i really need this view , thanks, ill open up a extra ticket for this one even, thanks

**Comment by vonH** [comment]
@washingleaves No - it's that simple. Please stop request it on here.
