### ISSUE TITLE
 [skin] enable fanart in the background in advanced launcher

### ISSUE THREAD

**Issue by washingleaves** [vonH/skin.xperience1080#39]
advanced launcher view > poster view , Posters are too small and the game fanart isnt visible in the background while hovering over a game , the background is simply a solid grey for all games its as if youve disabled fanart while in poster view, it does show in the gameinfo menue at the top left but not in the background neither outside in the background while scrolling through games ,a fix would be appreciated

**Comment by xhaggi** [comment]
I can't reproduce it or how can I disable the fanarts for AL

**Comment by washingleaves** [comment]
my bad , ive forgot to enable fanarts in the skin settings , lols
