### ISSUE TITLE
[osd] audio osd rework creates new issues

### ISSUE THREAD

**Issue by vonH** [vonH/skin.xperience1080#42]
Music OSD has issues and/or parts missing
- [x] audio channel flag is missing on info
- [x] with visualization on or off, the menu is under or nearly fully transparent
- [x] adding <onup>close</onup> brings the functionality in line with the video osd

**Comment by xhaggi** [comment]
> with visualization on or off, the menu is under or nearly fully transparent

fixed by 971b63c36480ddb68a517f77a1481326e69911cb

**Comment by xhaggi** [comment]
> audio channel flag is missing on info

done with e83d02f01073e9d71090c06f9500e7c56a6b09ba

@vonH I had to resize the audio osd flags to the same size the other flags are. Take a look at the commit and please do the necessary stuff for the flat theme. Thanks.

**Comment by xhaggi** [comment]
> adding close brings the functionality in line with the video osd

done with fefa592686396d69e0293263d3828a32e582f591
