### ISSUE TITLE
[skin] additional view , video wall view for xperience1080 ported from crnis 1080p mod, please

### ISSUE THREAD

**Issue by washingleaves** [vonH/skin.xperience1080#44]
i know vonH might not completely agree but i really need this additional view added to xperience1080 , its the video wall view from crnis 1080p mod , i would really appreciate it alot , i need this viewtype , since i use this as my main viewtype for going through all my movies , this is the only reason why im still using crnis 1080p mod , which as you can imagine is broken as all hell on kodis latest, again this would be a huge favour to me , thanks again

**Comment by vonH** [comment]
The answer is still no - no matter how many times you ask. It does not fit with the skin's aesthetics.
