### ISSUE TITLE
QuickNav is no longer working

### ISSUE THREAD

**Issue by vonH** [vonH/skin.xperience1080#46]
@xhaggi your menucontrol change appears to have killed this.

**Comment by xhaggi** [comment]
This is not an issue with the skin or Kodi. It's up to the user to customize his key mappings.

Default mapping for PlayerControls in Kodi's `keyboard.xml`

```
<n mod="ctrl">ActivateWindow(PlayerControls)</n>
```

and there is no default mapping for `remote.xml`. you need to adjust you remote.xml or keyboard.xml.

**Comment by vonH** [comment]
I misunderstood the menucontrol core change.
