### ISSUE TITLE
[home] widgets need to move to more robust handling method

### ISSUE THREAD

**Issue by vonH** [vonH/skin.xperience1080#51]
The widgets require a complete overhaul in order to add new features and make it easier for further changes.

**Comment by freeman212** [comment]
@vonH oh no :(

**Comment by vonH** [comment]
https://github.com/vonH/skin.xperience1080/commit/6aef5ef3cbb0a3ca639407055aed2730a3401069, https://github.com/vonH/skin.xperience1080/commit/7ff18dd5250aaceb5357d70dc53ba32a33ae12ed, https://github.com/vonH/skin.xperience1080/commit/2c87ca2cbdf457ce60113f465c85e984d8c3697b, https://github.com/vonH/skin.xperience1080/commit/99a1494042f32d2ccb7b5f25d1692d8339eed6ac

For reference.
