### ISSUE TITLE
Can´t return back to playing video

### ISSUE THREAD

**Issue by ttomovcik** [vonH/skin.xperience1080#53]
I don´t know if it´s only my problem (don´t know how to use it), ir it´s skin problem, but I can´t return back to video playing in backround. (Mybe key combination or something :+1: )

I´m using Kodi 16 Jarvis on Xubuntu Netbook as server

**Comment by vonH** [comment]
I use the Logitech K400 on all my devices, pressing backspace or escape works. Can you provide more information about your control?

**Comment by ttomovcik** [comment]
I have wireless keyboard and mouse (MK320), when I´m at home screen and I press escape or backspace, nothing works... I don´t know what to do, but I´m switching to Windows Server,  so will see ;)

**Comment by xhaggi** [comment]
not related to the skin please use the kodi forum to get help for your key mapping issue.
