### ISSUE TITLE
 Kodi (16.1) in rpi2/3, infinit GUI crash

### ISSUE THREAD

**Issue by mvillarejo** [vonH/skin.xperience1080#54]
Hello, 
first of all brilliant skin for kodi.

it seems that there is something wrong after latest upgrade, you can change to xperience skin with no issues but if you restart, GUI crashed all the time and you need to recover modifying .kodi/userdata/guisettings.xml to skin.osmc, any idea? tried with a clean installation and the same thing happened.

here there are some details of my setup

```
01:36:45  91.882599 T:1957143472  NOTICE: Starting Kodi (16.1). Platform: Linux ARM (Thumb) 32-bit
01:36:45  91.882668 T:1957143472  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
01:36:45  91.882736 T:1957143472  NOTICE: Kodi compiled May  3 2016 by GCC 4.9.2 for Linux ARM (Thumb) 32-bit version 3.16.7 (200711)
01:36:45  91.883041 T:1957143472  NOTICE: Running on Open Source Media Center 2016.05-1, kernel: Linux ARM 32-bit version 4.4.8-3-osmc
01:36:45  91.883110 T:1957143472  NOTICE: FFmpeg statically linked, version: 2.8.6-kodi-2.8.6-Jarvis-16.0
01:36:45  91.883171 T:1957143472  NOTICE: Host CPU: ARMv7 Processor rev 4 (v7l), 4 cores available
```

cheers

**Comment by mvillarejo** [comment]
Hello! anyone having similar issue? thanks.

**Comment by xhaggi** [comment]
should be fixed in the latest stable version

**Comment by mvillarejo** [comment]
thanks, working now!
