### ISSUE TITLE
Homescreen PVR widget launches the wrong TV channel when using some backends

### ISSUE THREAD

**Issue by JonathanHolvey** [vonH/skin.xperience1080#57]
I've found that when playing a PVR channel from the homescreen widget, the wrong channel is launched, when using TVheadend (and possibly VDR) as the PVR backend. Launching channels works fine from the normal channel list menu.

The difference seems to be the use of the method `CPVRDirectory.GetDirectory()` in the former, rather than `CGUIInfoManager.SetCurrentMovie()`.

Refer to this forum thread for further details http://forum.kodi.tv/showthread.php?tid=279315

**Comment by xhaggi** [comment]
could you please file the issue again in our new repo https://github.com/xperience1080/skin.xperience1080/issues
